Check min ttl
Metaswitch/cpp-common-test pull request #44
Opened 2017-02-21 13:46 UTC by KristaHyer

Added tests to check the correct min ttl is returned.

Min ttl checked in all pre-existing tests, and three new ones added:
o	Ttl explicitly set to 0 is returned as 0
o	Ttl returned correctly with empty and filled SRV
o	Ttl returned correctly with empty and filled NAPTR

All tests passed.

This is related to issue #265.

2017-02-21 20:13 UTC, eleanor-merry requested changes
Generally looks good. There's a couple of picky comments about formatting, and one more major one where the test result looks wrong.

2017-02-21 20:13 UTC, eleanor-merry commented on src/ut/diameterresolver_test.cpp
> +  void resolve(std::string expected_string, int expected_ttl)
expected_output rather than expected_string please

2017-02-21 20:13 UTC, eleanor-merry commented on src/ut/diameterresolver_test.cpp
> +    EXPECT_EQ(expected_string, output);
Line after }

2017-02-21 20:13 UTC, eleanor-merry commented on src/ut/diameterresolver_test.cpp
> +    "3.0.0.1:3868;transport=SCTP", 0);
Alignment of this is wrong (and for every test).

2017-02-21 20:13 UTC, eleanor-merry commented on src/ut/diameterresolver_test.cpp
> +TEST_F(DiameterResolverTest, MinTtlEmptySRV)
TTL not Ttl please

2017-02-21 20:13 UTC, eleanor-merry commented on src/ut/diameterresolver_test.cpp
> +     "3.0.0.1:3868;transport=SCTP", 800);
Is this the right TTL? Is this for the empty NAPTR?

2017-02-22 09:49 UTC, KristaHyer commented on src/ut/diameterresolver_test.cpp
> +  void resolve(std::string expected_string, int expected_ttl)
done

2017-02-22 09:49 UTC, KristaHyer commented on src/ut/diameterresolver_test.cpp
> +    EXPECT_EQ(expected_string, output);
done

2017-02-22 09:50 UTC, KristaHyer commented on src/ut/diameterresolver_test.cpp
> +TEST_F(DiameterResolverTest, MinTtlEmptySRV)
done

2017-02-22 10:04 UTC, KristaHyer commented on src/ut/diameterresolver_test.cpp
> +    "3.0.0.1:3868;transport=SCTP", 0);
done

2017-03-08 12:02 UTC, closed without merging